name: 下载JM本子1 (commit)

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/download1.yml' # 工作流定义
      - 'usage/workflow_download1.py' # 下载脚本
      - 'assets/option/option_workflow_download.yml' # 配置文件

jobs:
  crawler:
    runs-on: ubuntu-latest
    env:
      # 登录相关secrets
      JM_USERNAME: ${{ secrets.JM_USERNAME }}
      JM_PASSWORD: ${{ secrets.JM_PASSWORD }}

      # 邮件相关secrets
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TITLE: ${{ secrets.EMAIL_TITLE }}
      EMAIL_CONTENT: ${{ secrets.EMAIL_CONTENT }}
      
      # 固定值
      JM_DOWNLOAD_DIR: /home/runner/work/jmcomic/download/
      ZIP_NAME: '本子.tar.gz'
      UPLOAD_NAME: 'Click me to download'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: 安装jmcomic（pip）
        if: ${{ github.ref != 'refs/heads/dev' }}
        run: pip install jmcomic -i https://pypi.org/project --upgrade
      - name: 安装jmcomic（local）
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: pip install -e ./
      - name: 运行下载脚本
        run: |
          cd ./usage/
          python workflow_download.py
      - name: 压缩文件
        run: |
          cd $JM_DOWNLOAD_DIR
          tar -zcvf "../$ZIP_NAME" ./
          mv "../$ZIP_NAME" .
      - name: 自动释放
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1"
          prerelease: true
          title: "finder-result"
          files: ${{ env.JM_DOWNLOAD_DIR }}/${{ env.ZIP_NAME }}
      - name: Commit change
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git pull origin master
            git add ./usage/list2.txt
            git add ./usage/final_list.txt
            git commit -m "去重复和集合排序"
      - name: Push
        uses:  ad-m/github-push-action@master
        with:
            branch: master