name: 测试

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/去重复.yml' # 工作流定义
      - 'usage/1.py' # 下载脚本
      - 'assets/option/option_workflow_download.yml' # 配置文件

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: 运行下载脚本
        run: |
          cd ./usage/
          python 1.py
